# Generated by Django 4.1.1 on 2022-11-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waste_daily_transaction',
            name='waste_item_code',
            field=models.CharField(default='', max_length=100),
        ),
    ]
